We first start with some simple examples to see how clustering algorithm is working. Assume you have the below points with two dimentions: (1,2); (1,4); (1,0); (10,2); (10,4); (10,0)
lets looks at the points visually 

In [ ]:
import plotly.express as px
fig = px.scatter(x=[1,1,1,10,10,10], y=[ 2, 4, 0, 2,4,0])
fig.show()

I am sure you quickly detected two clusters, **Cluster 1:** points with the value of 1 and **Cluster 2:**points with the value of 10 on their X-axis. Lets run the K-means algorithm with k=2.

In [ ]:
>>> from sklearn.cluster import KMeans
>>> import numpy as np
>>> X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
>>> kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

Using the below code, you can find the cluster label for each points.

In [ ]:
>>> kmeans.labels_

array([1, 1, 1, 0, 0, 0, 0], dtype=int32)

also you can find the cluster of a given new points. lets do for (0,0) & (12,3). You can guess their cluster before running the algorithm. 

In [ ]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0], dtype=int32)

The clustering algorithm is working by finding the center of each cluster. So lets find the centers of these two clusters. 

In [ ]:
kmeans.cluster_centers_

array([[11.25,  2.75],
       [ 1.  ,  2.  ]])

Task 1. Now you can try by adding other points to the dataset to see how the clsutering formation will be changed: (50, 5). use k=2. 

In [ ]:
#add your code here

Lets see what you got.

In [ ]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0], [50,5]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.cluster_centers_
kmeans.predict([[0, 0], [50, 6]])

array([0, 1], dtype=int32)

Since (50,5) is very far from others, it formed its own cluster! in the real cases, you should delete suhc a point as an outlier. 
The real shortcoming of k-means algorithm is that you should enter number of clusters manually! but what is the optimum number of clusters?!! before introducing a solution, lets still work with our sample data. We can examine the K-means capability for three clusters using this dataset: (1,2); (1,4); (1,0); (10,2); (10,4); (10,0); (20, 1); (20, 2); (20,4)
Task 2. run the k-means and reflect on the results, does it make sense to you?
add your code:

In [ ]:
#add your code here

**Silhouette**:
using this approch, you can find the natural number of clusters. in a nutshel, silhouette of each point shows how closely it is matched to data within its cluster. Silhouette mean is between (-1,1). the more closets to one shows the chosen value of k is a good one. 
So in a simple term, you can compute silhouette metric for various values of k and the highest silhouette locate the optimum number of clusters. 

lest first see how you can compute the silhouette values. 

In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.7133477791749615

now lets see whether silhouette metric is usefull using a synthetic data: (1,2); (1,4); (1,0); (10,2); (10,4); (10,0); (20, 1); (20, 2); (20,4). As you can see the optimum value of k is 3, so the silhouette value of k=3 should be higehr than the one for k=2. 

In [ ]:
# silhouette metric for k=2
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0],[20, 1], [20, 2], [20, 4] ])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.6221622444438195

In [ ]:
# silhouette metric for k=3
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0],[20, 1], [20, 2], [20, 4] ])
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.7437105975720076

*   The silhouette value for k=3 is 0.73
*   the silhouette value for k=2 is 0.62

lets back to the outlier example! possibly silhouette metric is not able to help you! 

In [ ]:
# silhouette metric for k=2
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0], [50,5]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.728354899406882

In [ ]:
# silhouette metric for k=3
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0], [50,5]])
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.6114409535785384


    The silhouette value for k=3 is 0.61
    the silhouette value for k=2 is 0.72



so it means, the preprocessing step is essential for you! now let look at the case when we have just one point which is not outlier and deserve its own cluster!

In [ ]:
# silhouette metric for k=2
from sklearn.cluster import KMeans
import numpy as np
from sklearn.metrics import silhouette_samples, silhouette_score
X = np.array([[0, 2], [0, 4], [0, 0], [12, 2], [12, 4], [12, 0], [6,2]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg
#kmeans.predict([[5, 5], [1,2], [10,2]])

0.6156973720130201

In [ ]:
# silhouette metric for k=3
from sklearn.cluster import KMeans
import numpy as np
from sklearn.metrics import silhouette_samples, silhouette_score
X = np.array([[0, 2], [0, 4], [0, 0], [12, 2], [12, 4], [12, 0], [6,2]])
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.4908523910331865

The algorithm is preferring k=2, lets add one more data near to (6,2) and see whether the algorithm allows us to form three clusters or not!

In [ ]:
# silhouette metric for k=2
from sklearn.cluster import KMeans
import numpy as np
from sklearn.metrics import silhouette_samples, silhouette_score
X = np.array([[0, 2], [0, 4], [0, 0], [12, 2], [12, 4], [12, 0], [6,2], [6,1]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.5641358137112455

In [ ]:
# silhouette metric for k=2
from sklearn.cluster import KMeans
import numpy as np
from sklearn.metrics import silhouette_samples, silhouette_score
X = np.array([[0, 2], [0, 4], [0, 0], [12, 2], [12, 4], [12, 0], [6,2], [6,1]])
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
silhouette_avg = silhouette_score(X, kmeans.labels_)
silhouette_avg

0.6412694059293957

yes, now it makes sense to the algorithm! 